// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 * SecretProviderClass is the Schema for the secretproviderclasses API
 *
 * @schema SecretProviderClass
 */
export class SecretProviderClass extends ApiObject {
  /**
     * Returns the apiVersion and kind for "SecretProviderClass"
     */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'secrets-store.csi.x-k8s.io/v1',
    kind: 'SecretProviderClass',
  };

  /**
     * Renders a Kubernetes manifest for "SecretProviderClass".
     *
     * This can be used to inline resource manifests inside other objects (e.g. as templates).
     *
     * @param props initialization props
     */
  public static manifest(props: SecretProviderClassProps = {}): any {
    return {
      ...SecretProviderClass.GVK,
      ...toJson_SecretProviderClassProps(props),
    };
  }

  /**
     * Defines a "SecretProviderClass" API object
     * @param scope the scope in which to define this object
     * @param id a scope-local name for the object
     * @param props initialization props
     */
  public constructor(scope: Construct, id: string, props: SecretProviderClassProps = {}) {
    super(scope, id, {
      ...SecretProviderClass.GVK,
      ...props,
    });
  }

  /**
     * Renders the object to Kubernetes JSON.
     */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...SecretProviderClass.GVK,
      ...toJson_SecretProviderClassProps(resolved),
    };
  }
}

/**
 * SecretProviderClass is the Schema for the secretproviderclasses API
 *
 * @schema SecretProviderClass
 */
export interface SecretProviderClassProps {
  /**
     * @schema SecretProviderClass#metadata
     */
  readonly metadata?: ApiObjectMetadata;

  /**
     * SecretProviderClassSpec defines the desired state of SecretProviderClass
     *
     * @schema SecretProviderClass#spec
     */
  readonly spec?: SecretProviderClassSpec;

}

/**
 * Converts an object of type 'SecretProviderClassProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_SecretProviderClassProps(obj: SecretProviderClassProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_SecretProviderClassSpec(obj.spec),
  };
    // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * SecretProviderClassSpec defines the desired state of SecretProviderClass
 *
 * @schema SecretProviderClassSpec
 */
export interface SecretProviderClassSpec {
  /**
     * Configuration for specific provider
     *
     * @schema SecretProviderClassSpec#parameters
     */
  readonly parameters?: { [key: string]: string };

  /**
     * Configuration for provider name
     *
     * @schema SecretProviderClassSpec#provider
     */
  readonly provider?: string;

  /**
     * @schema SecretProviderClassSpec#secretObjects
     */
  readonly secretObjects?: SecretProviderClassSpecSecretObjects[];

}

/**
 * Converts an object of type 'SecretProviderClassSpec' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_SecretProviderClassSpec(obj: SecretProviderClassSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'parameters': ((obj.parameters) === undefined) ? undefined : (Object.entries(obj.parameters).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'provider': obj.provider,
    'secretObjects': obj.secretObjects?.map(y => toJson_SecretProviderClassSpecSecretObjects(y)),
  };
    // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * SecretObject defines the desired state of synced K8s secret objects
 *
 * @schema SecretProviderClassSpecSecretObjects
 */
export interface SecretProviderClassSpecSecretObjects {
  /**
     * annotations of k8s secret object
     *
     * @schema SecretProviderClassSpecSecretObjects#annotations
     */
  readonly annotations?: { [key: string]: string };

  /**
     * @schema SecretProviderClassSpecSecretObjects#data
     */
  readonly data?: SecretProviderClassSpecSecretObjectsData[];

  /**
     * labels of K8s secret object
     *
     * @schema SecretProviderClassSpecSecretObjects#labels
     */
  readonly labels?: { [key: string]: string };

  /**
     * name of the K8s secret object
     *
     * @schema SecretProviderClassSpecSecretObjects#secretName
     */
  readonly secretName?: string;

  /**
     * type of K8s secret object
     *
     * @schema SecretProviderClassSpecSecretObjects#type
     */
  readonly type?: string;

}

/**
 * Converts an object of type 'SecretProviderClassSpecSecretObjects' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_SecretProviderClassSpecSecretObjects(obj: SecretProviderClassSpecSecretObjects | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'annotations': ((obj.annotations) === undefined) ? undefined : (Object.entries(obj.annotations).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'data': obj.data?.map(y => toJson_SecretProviderClassSpecSecretObjectsData(y)),
    'labels': ((obj.labels) === undefined) ? undefined : (Object.entries(obj.labels).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'secretName': obj.secretName,
    'type': obj.type,
  };
    // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * SecretObjectData defines the desired state of synced K8s secret object data
 *
 * @schema SecretProviderClassSpecSecretObjectsData
 */
export interface SecretProviderClassSpecSecretObjectsData {
  /**
     * data field to populate
     *
     * @schema SecretProviderClassSpecSecretObjectsData#key
     */
  readonly key?: string;

  /**
     * name of the object to sync
     *
     * @schema SecretProviderClassSpecSecretObjectsData#objectName
     */
  readonly objectName?: string;

}

/**
 * Converts an object of type 'SecretProviderClassSpecSecretObjectsData' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_SecretProviderClassSpecSecretObjectsData(obj: SecretProviderClassSpecSecretObjectsData | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'objectName': obj.objectName,
  };
    // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */
